#!/usr/local/bin/ruby-271
# must be scheduled in crontab to run as the same user as oddb

$: << File.expand_path("../src", File.dirname(__FILE__))
$: << File.expand_path("..", File.dirname(__FILE__))

require "util/job"
require "util/updater"

module ODDB
  module Util
    Job.run do |system|
      opts = {
        fix_galenic_form: false,
        iksnrs: [],
        update_compositions: false,
        check: true
      }
      ARGV.each do |arg|
        if /fix_galenic_form/.match?(arg)
          opts[:fix_galenic_form] = true
        elsif /update_compositions/.match?(arg)
          opts[:update_compositions] = true
        elsif /^\d+$/.match?(arg)
          opts[:iksnrs] << arg.to_i if arg.size > 0
        end
      end
      puts "opts == #{opts.inspect}\n"
      updater = Updater.new system
      updater.update_swissmedic(opts)
    end
  end
end
