#!/usr/local/bin/ruby
# must be scheduled in crontab to run as the same user as oddb

$: << File.expand_path('../src', File.dirname(__FILE__))
$: << File.expand_path('..', File.dirname(__FILE__))

puts "ARGV is #{ARGV.inspect}"
require 'util/job'
require 'util/updater'

module ODDB
  module Util
    opts = {
      :lang  => :de,
      :files => [],
    }
    ARGV.each do |arg|
      if arg =~ /^fr$/i
        opts[:lang] = :fr
      else
        opts[:files] << arg if arg.size > 0
      end
    end
    opts[:files] = ["*.docx"] if opts[:files].size == 0
    puts "\nopts == #{opts.inspect}\n\n"
    Job.run do |system|
      Updater.new(system).update_medical_products(opts)
    end
  end
end
