#!/usr/local/bin/ruby-271
# must be scheduled in crontab to run as the same user as oddb

$: << File.expand_path('../src', File.dirname(__FILE__))
$: << File.expand_path('..', File.dirname(__FILE__))
require 'util/job'
require 'util/updater'
require "debug"
module ODDB
  module Util
    opts = {patinfo_only: false,
            fachinfo_only: false,}
    ARGV.each do |arg|
      opts[:patinfo_only] = true if arg =~ /(patinfo_only)$/
      opts[:fachinfo_only] = true if arg =~ /(fachinfo_only)$/
    end
    Job.run do |system|
      Updater.new(system).run(opts)
    end
  end
end
