#!/usr/local/bin/ruby-271
# must be scheduled in crontab to run as the same user as oddb
# FHIR NDJSON variant of import_bsv
# Downloads and processes the BAG SL export in FHIR NDJSON format
# instead of the traditional XMLPublications.zip

$: << File.expand_path("../src", File.dirname(__FILE__))
$: << File.expand_path("..", File.dirname(__FILE__))

require "util/job"
require "util/updater"

module ODDB
  module Util
    Job.run do |system|
      updater = Updater.new system
      if updater.update_bsv_fhir
        updater.update_bsv_followers
      end
    end
  end
end
