#!/usr/local/bin/ruby-271
# must be scheduled in crontab to run as the same user as oddb

$: << File.expand_path("../src", File.dirname(__FILE__))
$: << File.expand_path("..", File.dirname(__FILE__))
require "util/job"
require "util/updater"
require "debug"
module ODDB
  module Util
    opts = {patinfo_only: false,
            fachinfo_only: false}
    # force downloading everything via removing:
    # rm -v data/xml/*yml data/xml/swissmedicinfo.zip data/xml/AipsDownload_latest.xml AllHtml.zip data/AllHtm
    ARGV.each do |arg|
      opts[:skip] = true if /(skip)$/.match?(arg)
      opts[:patinfo_only] = true if /(patinfo_only)$/.match?(arg)
      opts[:fachinfo_only] = true if /(fachinfo_only)$/.match?(arg)
    end
    Job.run do |system|
      Updater.new(system).run(opts)
    end
  end
end
