#!/usr/local/bin/ruby-271
# must be scheduled in crontab to run as the same user as oddb

$: << File.expand_path("../src", File.dirname(__FILE__))
$: << File.expand_path("..", File.dirname(__FILE__))

require "util/job"
require "util/updater"

module ODDB
  module Util
    # FHIR NDJSON (FOPH/BAG) is the default source since June 2026, mirroring
    # oddb2xml. Opt out with --no-fhir to fall back to the legacy
    # XMLPublications.zip (Spezialitätenliste) import.
    use_fhir = !ARGV.delete("--no-fhir")
    Job.run do |system|
      updater = Updater.new system
      updated = use_fhir ? updater.update_bsv_fhir : updater.update_bsv
      if updated
        updater.update_bsv_followers
      end
    end
  end
end
