#!/usr/local/bin/ruby
# must be scheduled in crontab to run as the same user as oddb

$: << File.expand_path('../src', File.dirname(__FILE__))
$: << File.expand_path('..', File.dirname(__FILE__))

require 'util/job'
require 'util/updater'

module ODDB
  module Util
    Job.run do |system|
      name = ARGV.first
      puts "\nname == #{name}\n\n" if name
      system.rebuild_indices(name)
    end
  end
end
