#!/usr/local/bin/ruby-271
# must be scheduled in crontab to run as the same user as oddb

$: << File.expand_path("../src", File.dirname(__FILE__))
$: << File.expand_path("..", File.dirname(__FILE__))

require "util/job"
require "util/updater"

module ODDB
  module Util
    Job.run do |system|
      opts = {
        reparse: false
      }
      ARGV.each do |arg|
        if /reparse/.match?(arg)
          opts[:reparse] = true
        end
      end
      Updater.new(system).update_drugshortage(opts)
    end
  end
end
