#!/usr/local/bin/ruby
# must be scheduled in crontab to run as the same user as oddb

$: << File.expand_path('../src', File.dirname(__FILE__))
$: << File.expand_path('..', File.dirname(__FILE__))

require 'util/job'
require 'util/updater'

module ODDB
  module Util
    Job.run do |system|
      opts = {
        :target   => :fi,
        :reparse  => false,
        :iksnrs   => [],
        :companies => [],
        :download => true,
        :xml_file => nil, # if set will force download => false 
      }
      ARGV.each do |arg|
        if arg =~ /^\-\-(target|type)[\s=](fi|pi|both)$/
          opts[:target] = $2.intern
        elsif arg =~ /reparse/
          opts[:reparse] = true
        elsif arg =~ /no\-download/
          opts[:download] = false
        elsif arg =~ /xml_file=(\w.+)/
                 m = /xml_file=(\w.+)/.match(arg)
          opts[:xml_file] = m[1]
          opts[:download] = false
        elsif arg =~ /^\d{5}$/
          opts[:iksnrs] << arg
        else arg =~ /^\w*$/
          opts[:companies] << arg if arg.size > 0
        end
      end
      puts "\nopts == #{opts.inspect}\n\n"
      Updater.new(system).update_textinfo_swissmedicinfo(opts)
    end
  end
end
