#!/usr/local/bin/ruby
# must be scheduled in crontab to run as the same user as oddb

$: << File.expand_path('../src', File.dirname(__FILE__))
$: << File.expand_path('..', File.dirname(__FILE__))

require 'util/job'
require 'util/updater'

module ODDB
  module Util
    Job.run do |system|
      opts = {
        :target  => :fi,
        :reparse => false,
        :iksnrs  => [],
      }
      ARGV.each do |arg|
        if arg =~ /^\d{5}$/
          opts[:iksnrs] << arg
        elsif arg =~ /^\-\-target[\s=](fi|pi|both)$/
          opts[:target] = $1.intern
        elsif arg =~ /reparse/
          opts[:reparse] = true
        end
      end
      puts "\nopts == #{opts.inspect}\n\n"
      Updater.new(system).update_textinfo_swissmedicinfo(opts)
    end
  end
end
