#!/usr/bin/env ruby
# suite.rb -- oddb.org/ext -- 15.02.2011 -- mhatakeyama@ywesee.com 

require "./swissreg/test/test_writer.rb"
require "./swissreg/test/test_session.rb"
#require "./meddata/test/test_session.rb"
require "./meddata/test/test_result.rb"
require "./meddata/test/test_meddata.rb"
require "./meddata/test/test_ean_factory.rb"
require "./fiparse/test/test_patinfo_hpricot.rb"
require "./fiparse/test/test_fachinfo_hpricot.rb"
require "./comarketing/test/test_pdf_parser.rb"
require "./chapterparse/test/test_writer.rb"
require "./chapterparse/test/test_parser.rb"
require "./chapterparse/test/test_integrate.rb"
require "./analysisparse/test/test_simple_list_parser.rb"
require "./analysisparse/test/test_pagehandler.rb"
require "./analysisparse/test/test_list_parser.rb"
require "./analysisparse/test/test_fragmented_page_handler.rb"
require "./analysisparse/test/test_extended_list_parser.rb"
require "./analysisparse/test/test_block_list_parser.rb"
require "./analysisparse/test/test_appendix_parser.rb"
require "./analysisparse/test/test_antibody_list_parser.rb"
require "./analysisparse/test/test_anonymous_list_parser.rb"
require "./export/test/test_oddbdat.rb"
require "./export/test/test_generics_xls.rb"
require "./export/test/test_csv_exporter.rb"
require "./fiparse/test/test_fachinfo_doc_parser.rb"
