#!/usr/bin/env ruby
# suite.rb -- oddb.org/ext -- 11.04.2011 -- mhatakeyama@ywesee.com 

current_dir = (File.expand_path(File.dirname(__FILE__)))

require "#{current_dir}/swissreg/test/test_writer.rb"
require "#{current_dir}/swissreg/test/test_session.rb"
#require "./meddata/test/test_session.rb"
require "#{current_dir}/meddata/test/test_result.rb"
require "#{current_dir}/meddata/test/test_meddata.rb"
require "#{current_dir}/meddata/test/test_ean_factory.rb"
require "#{current_dir}/fiparse/test/test_patinfo_hpricot.rb"
require "#{current_dir}/fiparse/test/test_fachinfo_hpricot.rb"
require "#{current_dir}/fiparse/test/test_fachinfo_writer.rb"
require "#{current_dir}/comarketing/test/test_pdf_parser.rb"
require "#{current_dir}/chapterparse/test/test_writer.rb"
require "#{current_dir}/chapterparse/test/test_parser.rb"
require "#{current_dir}/chapterparse/test/test_integrate.rb"
require "#{current_dir}/analysisparse/test/test_simple_list_parser.rb"
require "#{current_dir}/analysisparse/test/test_pagehandler.rb"
require "#{current_dir}/analysisparse/test/test_list_parser.rb"
require "#{current_dir}/analysisparse/test/test_fragmented_page_handler.rb"
require "#{current_dir}/analysisparse/test/test_extended_list_parser.rb"
require "#{current_dir}/analysisparse/test/test_block_list_parser.rb"
require "#{current_dir}/analysisparse/test/test_appendix_parser.rb"
require "#{current_dir}/analysisparse/test/test_antibody_list_parser.rb"
require "#{current_dir}/analysisparse/test/test_anonymous_list_parser.rb"
require "#{current_dir}/export/test/test_oddbdat.rb"
require "#{current_dir}/export/test/test_generics_xls.rb"
require "#{current_dir}/export/test/test_csv_exporter.rb"
require "#{current_dir}/fiparse/test/test_fachinfo_doc_parser.rb"
require "#{current_dir}/readonly/test/test_readonly_server.rb"
